### ISSUE TITLE
Session time question

### ISSUE THREAD

**Issue by garkuwa** [robisim74/Angular2SPAWebAPI#15]
Hi,

I wondered if there is any logic for configuring session time. I would like to make session 20 minutes and logout user, if user didn't show any activity during this 20 minutes. As I understand, I might configure it thru scheduleTokenRefresh() and unscheduleRefresh() with additional logic. Please correct me if I'm wrong. 

Best regards,
Taras

**Comment by robisim74** [comment]
Hi Taras,

unscheduling is easy: just call `unscheduleRefresh` method, or rather, `signout` method, otherwise the user remains authenticated until the token expires.
The logic to track the user's activity there isn't in this sample: I think you could use a library like this:  https://github.com/HackedByChinese/ng2-idle

**Comment by garkuwa** [comment]
Thanks a lot for a quick reply!
